version: '3.1'

services:

  podis:
    build: ./
    environment:
      XDEBUG_MODE: 'debug'
      APP_ENV: 'dev'
      APP_DEBUG: 'true'
      XDEBUG_CONFIG: 'client_host=${XDEBUG_REMOTE_HOST:-host.docker.internal}'
    ports:
      - "4200:80"
    networks:
      podis-network:
    volumes:
      - ./:/var/www/html

networks:
  podis-network:

volumes:
  podis-network:
